version: '3'
services:
  PMS:
    image: spring:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@//192.168.1.245:1521/LACONIC
      - spring.datasource.username=pms
      - spring.datasource.password=pms
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.hibernate.ddl-auto=create-drop
      - keycloak.base.url=http://192.168.1.245:9000
      - keycloak.realm=LACONIC
      - keycloak.client=LACONIC